version: "3.8"
services:
  db:
    image: postgres
    container_name: workday-api-postgres
    environment:
      - POSTGRES_DB=workday
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: workday-api-app
    depends_on:
      - db
    ports:
      - "3000:3000"
